# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: CC0-1.0

paths-ignore:
  - minisign_dummy_keypair/minisign.key
  - minisign_dummy_keypair/minisign.pub
  - "@kaito-tokyo/*/test_fixtures/*.minisig"
