version = 1

[[annotations]]
path = [
  "package.json",
  "package-lock.json",
  "@kaito-tokyo/*/package.json",
  "@kaito-tokyo/*/package-lock.json",
  ".node-version",
  "tsconfig.base.json",
  "@kaito-tokyo/*/tsconfig.json",
]
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "CC0-1.0"
