# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Audit PR

on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        type: string

jobs:
  add-audit-to-pr:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: read

    env:
      BRANCH: audit/pr-stamp

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.BRANCH }}
          persist-credentials: true
          fetch-depth: 0

      - shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          AUDIT_FILENAME: "audit-pr-${{ inputs.pr-number }}-runid-${{ github.run_id }}.txt"
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ inputs.pr-number }}
        run: |
          GH_REPO_CONTENT_CREATE_ARGS=(
            --method PUT
            -H "Accept: application/vnd.github+json"
            -H "X-GitHub-Api-Version: 2026-03-10"
            "/repos/$GITHUB_REPOSITORY/contents/$AUDIT_FILENAME"
            -f "message=$AUDIT_FILENAME"
            -f "content=$(gh pr view "$PR_NUMBER" | base64 -w 0)"
          )
          gh api "${GH_REPO_CONTENT_CREATE_ARGS[@]}"





